version: "3.8"

services:
  fastapi-backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: fastapi-backend
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./FastAPI:/app/FastAPI
      - ./output:/app/output
      - ./test-data:/app/test-data
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    stdin_open: true
    tty: true
    ports:
      - "8001:8000"