version: "3.8"

services:
  document-generator:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: document-generator
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./FastAPI:/app/FastAPI
      - ./tmp_uploads:/app/tmp_uploads
      - ./charts:/app/charts
      - ./exports:/app/exports
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    stdin_open: true
    tty: true
    ports:
      - "8001:8000"