# import environment variables
from dotenv import load_dotenv
_ = load_dotenv()
import os
import json

# standard imports
from pydantic import BaseModel
from langgraph.graph import StateGraph, END
from typing import TypedDict, List, Dict
from langchain_core.messages import SystemMessage, HumanMessage
from openai import AzureOpenAI

from tavily import TavilyClient
from phoenix.otel import register
from opentelemetry.trace import StatusCode

from FastAPI.core.pdf_creator import save_to_pdf
from FastAPI.core.database_agent_2 import parts_summary, top_5_parts_by_price, top_5_part_distrubution_by_country, parts_average_price



load_dotenv()
pheonix_key = os.getenv("PHOENIX_API_KEY")
pheonix_collector_endpoint = os.getenv("PHOENIX_COLLECTOR_ENDPOINT")

# configure the Phoenix tracer
tracer_provider = register(
  project_name="my-llm-app", # Default is 'default'
  auto_instrument=True, # See 'Trace all calls made to a library' below
)
tracer = tracer_provider.get_tracer(__name__)

# setup inmemory sqlite checkpointers
import sqlite3
from langgraph.checkpoint.sqlite import SqliteSaver

conn = sqlite3.connect(":memory:", check_same_thread=False)
memory = SqliteSaver(conn)

# keeping
class AgentState(TypedDict):
    # human input
    task: str
    # plan the planning agent will generate
    plan: str
    # draft of the report
    draft: str
    # critique agent will populate this key
    critique: str
    # documents tavily has come back with
    web_content: List[str]
    # information from the database
    db_content: List[str]
    # path to the chart generated by the database_plan_node
    chart_metadata: List[Dict[str, str]]
    # keep track of how many times we've gone through the loop
    revision_number: int
    max_revisions: int

from langchain_openai import ChatOpenAI
# creating model
# temperature of 0 will make it very deterministic
model = ChatOpenAI(model="gpt-4o", temperature=0)

# prompt for llm that is going to write out the plan for the essay
PLAN_PROMPT = """You are an expert research analyst tasked with writing a high level outline of an automotive supply \
chain report. Write such an outline for the user provided topic using the sections below. Give an \
outline of the essay along with any relevant notes or instructions for the sections. 

    1. Executive Summary
    2. Introduction
    3. Overview of the braking system component
    4. Supply chain structure
    5. Risk Assessment
    6. Conclusion and Recommendations
    7. References
    8. Appendices

"""

# writing the essay given the information that was researched
WRITER_PROMPT = """You are a research analyst tasked with writing a report of at least 800 words with a maximum of \
1000 word report. \
Generate the best report possible for the user's request and the initial outline. Making sure to include any \
charts available in the body of the report. If the user provides critique, respond with a revised version \
of your previous attempts. Provide the output in a JSON format using the structure below. \

{{
      "title": "<Report Title>",
      "sections": [
        {{
          "heading": "<Section Heading>",
          "content": "<Plain text or markdown content>",
          "subsections": [
            {{
              "heading": "<Subsection Heading>",
              "content": "<Plain text or markdown content>"
            }}
          ]
        }}
      ]
    }}
    
The charts should be included using placeholders like [[FIGURE:<chart_id>]] in part of the report where the chart \
should appear. These placeholders will be replaced with the actual figures in the final report. \

Referencing should use Harvard Style. \

Utilize all the information below as needed: 



------

{content}"""

# control how we are critiqing the draft of the essay
REFLECTION_PROMPT = """You are a manager reviewing the analysts report. \
Generate critique and recommendations for the analysts submission. \
Provide detailed recommendations, including requests for length, depth, style, etc."""

DATABASE_PLAN_INSTRUCTIONS = """ You are a supply chain data analyst with access to several \
database tools. Your role is to extract relevant automotive part insights that will inform a \
detailed written report. Do not hallucinate numbers. Only use tool outputs.
"""

# given a plan will generate a bunch of queries and pass to tavily
RESEARCH_PLAN_PROMPT = """You are a researcher charged with providing information that can \
be used when writing the following essay. Generate a list of search queries that will gather \
any relevant information. Only generate 3 queries max."""

# after we've made the critique will pass the list of queries to pass to tavily
RESEARCH_CRITIQUE_PROMPT = """You are a researcher charged with providing information that can \
be used when making any requested revisions (as outlined below). \
Generate a list of search queries that will gather any relevant information. Only generate 3 queries max."""

# for generating a list of queries to pass to tavily will use function calling so we get a list of strings
# from tavily

class ResearchQueries(BaseModel):
    queries: List[str]

class DBQueries(BaseModel):
    queries: List[str]

# importing taviliy as using it in a slightly unconventional way
tavily = TavilyClient(api_key=os.environ["TAVILY_API_KEY"])

# take in the state and create list of messages, one of them is going to be the planning prompt
# then create a human message which is what we want system to do
@tracer.chain
def plan_node(state: AgentState):
    messages = [
        SystemMessage(content=PLAN_PROMPT),
        HumanMessage(content=state['task'])
    ]
    # pass these messages to the model
    response = model.invoke(messages)
    # get the content of the messages and pass to the plan key
    return {"plan": response.content}

@tracer.chain
def database_plan_node(state: AgentState):

    client = AzureOpenAI(
        azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
        api_key=os.getenv("AZURE_OPENAI_API_KEY"),
        api_version="2024-05-01-preview"
    )

    tools = [
        {
            "type": "function",
            "function": {
                "name": "parts_summary",
                "description": "Summarizes product groups by price, count, and origin.",
                "parameters": {"type": "object", "properties": {}, "required": []}
            }
        },
        {
            "type": "function",
            "function": {
                "name": "top_5_parts_by_price",
                "description": "Top 5 product groups by average price.",
                "parameters": {"type": "object", "properties": {}, "required": []}
            }
        },
        {
            "type": "function",
            "function": {
                "name": "top_5_part_distrubution_by_country",
                "description": "Top 5 countries by part distribution.",
                "parameters": {"type": "object", "properties": {}, "required": []}
            }
        },
        {
            "type": "function",
            "function": {
                "name": "parts_average_price",
                "description": "Returns average price of each part grouped by productGroupId.",
                "parameters": {"type": "object", "properties": {}, "required": []}
            }
        }
    ]

    available_functions = {
        "parts_summary": parts_summary,
        "top_5_parts_by_price": top_5_parts_by_price,
        "top_5_part_distrubution_by_country": top_5_part_distrubution_by_country,
        "parts_average_price": parts_average_price
    }

    assistant = client.beta.assistants.create(
        name="DB Assistant",
        instructions=DATABASE_PLAN_INSTRUCTIONS,
        tools=tools,
        model="gpt-4o"
    )

    thread = client.beta.threads.create()

    run = client.beta.threads.runs.create_and_poll(
        thread_id=thread.id,
        assistant_id=assistant.id,
        instructions=state["task"],
        tool_choice="auto"
    )

    tool_outputs = []
    collected_outputs = []

    if run.status == "requires_action":
        print("Assistant requested tools:", [
            tool_call.function.name for tool_call in run.required_action.submit_tool_outputs.tool_calls
        ])
        for tool_call in run.required_action.submit_tool_outputs.tool_calls:
            with tracer.start_as_current_span(
                    f"ToolCall: {tool_call.function.name}",
                    openinference_span_kind="tool",
                    attributes={"tool_name": tool_call.function.name}
            ) as span:
                fn = available_functions.get(tool_call.function.name)
                args = json.loads(tool_call.function.arguments)
                span.set_input(value=args)
                output = fn(**args) if args else fn()
                span.set_output(value={
                    "rows": len(output) if isinstance(output, list) else 0,
                    "type": type(output).__name__
                })

            collected_outputs.append({
                "tool_call_id": tool_call.id,
                "name": tool_call.function.name,
                "data": output
            })

            tool_outputs.append({
                "tool_call_id": tool_call.id,
                "output": json.dumps(output)
            })

        run = client.beta.threads.runs.submit_tool_outputs_and_poll(
            thread_id=thread.id,
            run_id=run.id,
            tool_outputs=tool_outputs
        )

    # Try to find parts_summary output for graphing
    target_output = next((t for t in collected_outputs if t["name"] == "parts_average_price"), None)

    if target_output:

        formatted_json = json.dumps(target_output["data"], indent=2)

        # Create chart assistant
        chart_assistant = client.beta.assistants.create(
            name="ChartPlotter",
            instructions="You are a data assistant who generates Python code to plot data.",
            tools=[{"type": "code_interpreter"}],
            model="gpt-4o"
        )

        # Start thread and send message
        thread_chart = client.beta.threads.create()

        client.beta.threads.messages.create(
            thread_id=thread_chart.id,
            role="user",
            content=f"""Here is a list of average part prices in JSON format:

            {formatted_json}

            Use matplotlib to plot a bar chart using this data.
            The x-axis should be partDescription and the y-axis should be averagePrice.
            Return the chart as a PNG image. 
            """
        )

        run = client.beta.threads.runs.create_and_poll(
            thread_id=thread_chart.id,
            assistant_id=chart_assistant.id
        )

        # Extract image
        image_file_id = None
        messages = client.beta.threads.messages.list(thread_id=thread_chart.id)
        print("IMG messages: ", messages)
        image_file_id = None

        for msg in messages.data:
            # Option 1: Check for 'image_file' block type (if it exists in future responses)
            for content in getattr(msg, "content", []):
                if getattr(content, "type", None) == "image_file":
                    image_file_id = content.image_file.file_id
                    break

            # Option 2: Check for attachments (your actual scenario)
            if not image_file_id:
                for attachment in getattr(msg, "attachments", []):
                    if hasattr(attachment, "file_id"):
                        image_file_id = attachment.file_id
                        break

            if image_file_id:
                break

        print("Image file id: ", image_file_id)
        if image_file_id:
            # Save image locally
            image_bytes = client.files.with_raw_response.retrieve_content(image_file_id)
            plot_path = "parts_plot.png"
            with open(plot_path, "wb") as f:
                f.write(image_bytes.content)
            absolute_path = os.path.abspath(plot_path)
            graph_output = f"Chart generated and saved to {absolute_path}"
        else:
            graph_output = "(Chart generation failed: no image file returned)"
    else:
        graph_output = "(No parts_average_price output to visualize)"

    try:
        messages = client.beta.threads.messages.list(thread_id=thread.id)
        final_message = messages.data[0].content[0].text.value
    except (IndexError, AttributeError):
        final_message = "(No database output)"

    chart_metadata = []
    if target_output and image_file_id:
        chart_metadata.append({
            "id": "parts_average_price",
            "path": absolute_path,
        })

    return {
        "db_content": state.get("db_content", []) + [final_message, graph_output],
        "chart_metadata": state.get("chart_metadata", []) + chart_metadata
    }

# takes in the plan and does some research
@tracer.chain
def research_plan_node(state: AgentState):
    # response with what we will invoke this with is the
    # response will be pydantic model which has the list of queries
    queries = model.with_structured_output(ResearchQueries).invoke([
        # researching planning prompt and planning prompt
        SystemMessage(content=RESEARCH_PLAN_PROMPT),
        HumanMessage(content=state['task'])
    ])
    # original content
    content = state['web_content'] or []
    # loop over the queries and search for them in Tavily
    for q in queries.queries:
        with tracer.start_as_current_span(
                "TavilySearch",
                openinference_span_kind="tool",
                attributes={"query": q}
        ) as span:
            span.set_input(value=q)
            response = tavily.search(query=q, max_results=2)
            span.set_output(value=response)
            for r in response['results']:
                # get the list of results and append them to the content
                content.append(f"Source: {r['url']}\n{r['content']}")
    # return the content key which is equal to the original content plus the accumulated content
    return {"web_content": content}

@tracer.chain
def generation_node(state: AgentState):
    # prepare the content - list of strings and join them into one big one
    db = "\n\n".join(state.get("db_content", []))
    web = "\n\n".join(state.get("web_content", []))
    charts = "\n\n".join([f"Include these chart in the report: \n[[FIGURE:{item['id']}]]" for item in state.get("chart_metadata", [])])
    combined = f"### Database Insights:\n\n{db}\n\n---\n\n### Web Research:\n\n{web}\n\n---\n\n# Charts: \n\n{charts}"
    # create user message which combines the task and the plan
    user_message = HumanMessage(
        # task and plan
        content=f"{state['task']}\n\nHere is my plan:\n\n{state['plan']}")
    messages = [
        # format in documents which has been fetched
        SystemMessage(
            content=WRITER_PROMPT.format(content=combined)
        ),
        # task and the plan
        user_message
        ]
    response = model.invoke(messages)
    return {
        # update the draft with response and add 1 to the current revision number in the state
        "draft": response.content,
        "revision_number": state.get("revision_number", 1) + 1
    }

@tracer.chain
def reflection_node(state: AgentState):
    messages = [
        # take the reflection node and the draft
        SystemMessage(content=REFLECTION_PROMPT),
        HumanMessage(content=state['draft'])
    ]
    response = model.invoke(messages)
    # going to generate the critique
    return {"critique": response.content}

@tracer.chain
def research_critique_node(state: AgentState):
    queries = model.with_structured_output(ResearchQueries).invoke([
        SystemMessage(content=RESEARCH_CRITIQUE_PROMPT),
        HumanMessage(content=state['critique'])
    ])
    # get the original content and append with new queries
    content = state['web_content'] or []
    for q in queries.queries:
        with tracer.start_as_current_span(
                "TavilySearch",
                openinference_span_kind="tool",
                attributes={"query": q}
        ) as span:
            span.set_input(value=q)
            response = tavily.search(query=q, max_results=2)
            span.set_output(value=response)
            for r in response['results']:
                content.append(r['content'])
    return {"web_content": content}

# look at the revision number - if greater than the max revisions will then end.
def should_continue(state):
    with tracer.start_as_current_span(
            "ShouldContinueCheck",
            openinference_span_kind="chain"
    ) as span:
        span.set_input(value=state)
        if state["revision_number"] > state["max_revisions"]:
            print(save_to_pdf(content=state["draft"], filename="report.pdf", chart_metadata=state.get("chart_metadata", [])))
            result = END
        else:
            result = "reflect"
        span.set_output(value=result)
        return result

# initialise the graph with the agent state
builder = StateGraph(AgentState)

# add all nodes
builder.add_node("planner", plan_node)
builder.add_node("generate", generation_node)
builder.add_node("reflect", reflection_node)
builder.add_node("research_plan", research_plan_node)
builder.add_node("db_plan", database_plan_node)
builder.add_node("research_critique", research_critique_node)

# set entry point
builder.set_entry_point("planner")

# add conditional edge
builder.add_conditional_edges(
    "generate",
    should_continue,
    {END: END, "reflect": "reflect"}
)

# add in basic edges
builder.add_edge("planner", "db_plan")
builder.add_edge("db_plan", "research_plan")
builder.add_edge("research_plan", "generate")

builder.add_edge("reflect", "research_critique")
builder.add_edge("research_critique", "generate")

# compile graph and add in checkpointer
graph = builder.compile(checkpointer=memory)

# from IPython.display import Image
#
# Image(graph.get_graph().draw_png())

# save the graph
output_graph_path = "langgraph.png"
with open(output_graph_path, "wb") as f:
    f.write(graph.get_graph().draw_mermaid_png())


def run_agent(messages):
    with (tracer.start_as_current_span(
            "LangGraphExecution",
            openinference_span_kind="chain")
    as span):
        span.set_input(value=messages)

        # adding in graph.stream so can see all the steps
        thread = {"configurable": {"thread_id": "1"}}
        for s in graph.stream({
            'task': messages,
            "max_revisions": 2,
            "revision_number": 1,
            "db_content": [],
            "web_content": [],
        }, thread):
            print(s)
        span.set_status(StatusCode.OK)


# start from the outermost layer and work your way down so you capture the right info
# only just calling this run_agent span and calls to add tracing
def start_main_span(messages):
    print("Starting main span with messages:", messages)

    # span_kind maps to colors etc...
    # anything in the with cause block will be treated as part of that span
    with tracer.start_as_current_span(
            "AgentRun", openinference_span_kind="agent"
    ) as span:
        # setting the input
        span.set_input(value=messages)
        ret = run_agent(messages)
        print("Main span completed with return value:", ret)
        # setting the output
        span.set_output(value=ret)
        # set status call - called correctly
        span.set_status(StatusCode.OK)
        return ret

start_main_span("Write me a report on the supply chain of the Toyota RAV4 braking system")


