from typing import TypedDict, List, Dict, Annotated, Optional, Any
from langchain_core.messages import AnyMessage, BaseMessage
from langgraph.graph.message import add_messages
from datetime import datetime

# Magentic-One Task Ledger structure
class TaskLedger(TypedDict):
    facts: List[str]  # Verified information from analysis
    hypotheses: List[str]  # Working assumptions being tested
    current_plan: Dict[str, Any]  # Current execution plan with steps and rationale

# Magentic-One Progress Ledger entry structure
class ProgressEntry(TypedDict):
    agent: str  # Which agent performed the action
    action: str  # What action was performed
    timestamp: str  # When it happened
    success: bool  # Whether it succeeded
    details: str  # Description of what happened
    artifacts: Optional[List[str]]  # Any outputs/data produced
    stall_reason: Optional[str]  # If failed, why it stalled

class AgentState(TypedDict):
    # human input
    task: str
    # plan the planning agent will generate
    plan: str
    # draft of the report
    draft: str
    # critique agent will populate this key
    critique: str
    # documents tavily has come back with
    web_content: List[str]
    # information from the database
    db_content: Annotated[List[AnyMessage], add_messages]
    db_summary: str
    trajectory: List[str]
    # information from running the simulation
    raw_simulation: Annotated[List[BaseMessage], add_messages]
    clean_simulation: str
    # keep track of how many times we've gone through the loop
    revision_number: int
    max_revisions: int
    # chart generation
    chart_plan: List[Dict[str, str]]
    # path to the chart generated by the database_plan_node
    chart_metadata: List[Dict[str, str]]

    # to delete all of these
    current_chart_index: int
    chart_code: str
    chart_generation_success: bool
    chart_generation_error: str
    chart_retry_count: int
    max_chart_retries: int

    articles_path: str
    parts_path: str
    tariff_path: str
    # required by the supervisor
    messages: Annotated[List[AnyMessage], add_messages]
    remaining_steps: int
    # Magentic-One coordination fields
    coordination_decision: str
    trajectory: List[str]

    # Database plan progress tracking
    current_db_step: int
    total_db_steps: int
    db_plan_complete: bool

    # Magentic-One Ledgers
    task_ledger: TaskLedger
    progress_ledger: List[ProgressEntry]